server:
  port: 8775
eureka:
  client:
    serviceUrl:
      defaultZone: @eureka-server-1-url@,@eureka-server-2-url@
spring:
  application:
    name: service-feign-hystrix

#虽然写的时候没有这个属性的提示。但是其实是有的
#表示在消费端是否开启对服务的降级处理。即在服务端设置@FeignClient并设置回调函数是否要生效
#Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它，在配置文件加以下代码：
feign:
  hystrix:
    enabled: true

# springboot的Actuator提供了运行状态监控的功能，可以通过REST、远程Shell和JMX方式来查看。
# 这个配置非常重要，否则会导致/actuator/hystrix.stream无法访问,hystrix.stream节点会持续提供熔断状态
management:
  endpoints:
    web:
      #      2.0之前默认是/   2.0默认是 /actuator
      #      base-path: /actuator
      #      显示健康具体信息  默认不会显示详细信息
      #      management.endpoint.health.show-details=always
      exposure:
        # 默认开启health、info，可以通过/actuator/info访问,如果要暴露所有接口,填"*"
        include: hystrix.stream
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
