server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false       #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（集群模式）。
      #@key@通过这种方式可以获取到pom文件里面的一些属性
      defaultZone: @eureka-server-2-url@

#服务于服务之间都是通过这个名字来的，非常重要
spring:
  application:
    name: eurka-server-1